dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py36_0
  - alabaster=0.7.10=py36_0
  - anaconda=5.2.0=py36_3
  - anaconda-client=1.6.14=py36_0
  - anaconda-navigator=1.8.7=py36_0
  - anaconda-project=0.8.2=py36_0
  - asn1crypto=0.24.0=py36_0
  - astroid=1.6.3=py36_0
  - astropy=3.0.2=py36_1
  - attrs=18.1.0=py36_0
  - babel=2.5.3=py36_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py36_1
  - backports.shutil_get_terminal_size=1.0.0=py36_2
  - beautifulsoup4=4.6.0=py36_1
  - bitarray=0.8.1=py36_0
  - bkcharts=0.2=py36_0
  - blas=1.0=mkl
  - blaze=0.11.3=py36_0
  - bleach=2.1.3=py36_0
  - blosc=1.14.3
  - bokeh=0.12.16=py36_0
  - boto=2.48.0=py36_1
  - bzip2=1.0.6
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_1
  - click=6.7=py36_0
  - cloudpickle=0.5.3=py36_0
  - clyent=1.2.2=py36_1
  - colorama=0.3.9=py36_0
  - conda=4.5.4=py36_0
  - conda-build=3.10.5=py36_0
  - conda-env=2.6.0
  - conda-verify=2.0.0=py36_0
  - console_shortcut=0.1.1
  - contextlib2=0.5.5=py36_0
  - cryptography=2.2.1
  - curl=7.60.0
  - cycler=0.10.0=py36_0
  - cython=0.28.2=py36_0
  - cytoolz=0.9.0.1=py36_0
  - dask=0.17.5=py36_0
  - dask-core=0.17.5=py36_0
  - datashape=0.5.4=py36_0
  - decorator=4.3.0=py36_0
  - distributed=1.21.8=py36_0
  - docutils=0.14=py36_0
  - entrypoints=0.2.3=py36_2
  - et_xmlfile=1.0.1=py36_0
  - filelock=3.0.4=py36_0
  - flask=1.0.2=py36_1
  - flask-cors=3.0.4=py36_0
  - freetype=2.8
  - get_terminal_size=1.0.0
  - glob2=0.6=py36_0
  - greenlet=0.4.13=py36_0
  - h5py=2.7.1=py36_2
  - heapdict=1.0.0=py36_2
  - html5lib=1.0.1=py36_0
  - idna=2.6=py36_1
  - imageio=2.3.0=py36_0
  - imagesize=1.0.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.1=py36_0
  - isort=4.3.4=py36_0
  - itsdangerous=0.24=py36_1
  - jdcal=1.4=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36_0
  - jpeg=9b
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py36_0
  - jupyterlab=0.32.1=py36_0
  - jupyterlab_launcher=0.10.5=py36_0
  - kiwisolver=1.0.1=py36_0
  - lazy-object-proxy=1.3.1=py36_0
  - libcurl=7.60.0
  - libiconv=1.15
  - libpng=1.6.34
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - locket=0.2.0=py36_1
  - lxml=4.2.1=py36_0
  - lzo=2.10
  - matplotlib=2.2.2=py36_1
  - numpy=1.14.3=py36_1
  - numpy-base=1.14.3=py36_1
  - numpydoc=0.8.0=py36_0
  - pandas=0.23.0=py36_0
  - python=3.6.5
  - scikit-image=0.13.1=py36_1
  - scikit-learn=0.19.1=py36_0
  - tk=8.6.7
  - toolz=0.9.0=py36_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - typing=3.6.4=py36_0

  - pip:
    - tables==3.4.3
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
