dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - asn1crypto=0.24.0
  - astroid=1.6.3
  - astropy=3.0.2
  - attrs=18.1.0
  - babel=2.5.3
  - backcall=0.1.0
  - beautifulsoup4=4.6.0
  - bitarray=0.8.1
  - bkcharts=0.2
  - blas=1.0=mkl
  - blaze=0.11.3 
  - bleach=2.1.3 
  - blosc=1.14.3
  - bokeh=0.12.16 
  - boto=2.48.0  
  - bzip2=1.0.6
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16 
  - cffi=1.11.5 
  - chardet=3.0.4  
  - click=6.7 
  - cloudpickle=0.5.3 
  - clyent=1.2.2  
  - colorama=0.3.9 
  - conda=4.5.4 
  - conda-build=3.10.5 
  - conda-env=2.6.0
  - conda-verify=2.0.0 
  - console_shortcut=0.1.1
  - contextlib2=0.5.5 
  - cryptography=2.2.1
  - curl=7.60.0
  - cycler=0.10.0 
  - cython=0.28.2 
  - cytoolz=0.9.0.1 
  - dask=0.17.5 
  - dask-core=0.17.5 
  - datashape=0.5.4 
  - decorator=4.3.0 
  - distributed=1.21.8 
  - docutils=0.14 
  - entrypoints=0.2.3 
  - et_xmlfile=1.0.1 
  - filelock=3.0.4 
  - flask=1.0.2  
  - flask-cors=3.0.4 
  - freetype=2.8
  - get_terminal_size=1.0.0
  - glob2=0.6 
  - greenlet=0.4.13 
  - h5py=2.7.1 
  - heapdict=1.0.0 
  - html5lib=1.0.1 
  - idna=2.6  
  - imageio=2.3.0 
  - imagesize=1.0.0 
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2 
  - ipython=6.4.0 
  - ipython_genutils=0.2.0 
  - ipywidgets=7.2.1 
  - isort=4.3.4 
  - itsdangerous=0.24  
  - jdcal=1.4 
  - jedi=0.12.0  
  - jinja2=2.10 
  - jpeg=9b
  - jsonschema=2.6.0 
  - jupyter=1.0.0
  - jupyter_client=5.2.3 
  - jupyter_console=5.2.0  
  - jupyter_core=4.4.0 
  - jupyterlab=0.32.1 
  - jupyterlab_launcher=0.10.5 
  - kiwisolver=1.0.1 
  - lazy-object-proxy=1.3.1 
  - libcurl=7.60.0
  - libiconv=1.15
  - libpng=1.6.34
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - locket=0.2.0  
  - lxml=4.2.1 
  - lzo=2.10
  - matplotlib=2.2.2  
  - numpy=1.14.4
  - numpy-base=1.14.4
  - numpydoc=0.8.0
  - pandas=0.23.0
  - python=3.6.5
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - tk=8.6.7
  - toolz=0.9.0
  - tornado=5.0.2
  - traitlets=4.3.2
  - typing=3.6.4

  - pip:
    - tables==3.4.3
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
