dependencies:
  - python=3.6.5
  - imageio=2.3.0 
  - imagesize=1.0.0 
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2 
  - ipython=6.4.0 
  - ipython_genutils=0.2.0 
  - ipywidgets=7.2.1 
  - jupyter=1.0.0
  - jupyter_client=5.2.3 
  - jupyter_console=5.2.0  
  - jupyter_core=4.4.0 
  - jupyterlab=0.32.1 
  - jupyterlab_launcher=0.10.5 
  - matplotlib=2.2.2  
  - numpy=1.14.4
  - numpy-base=1.14.4
  - numpydoc=0.8.0
  - pandas=0.23.0
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - pip:
    - tables==3.4.3
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
